name: waktu_solat_malaysia
description: Ini ialah pakej untuk mendapatkan waktu solat di Malaysia berdasarkan jadual daripada JAKIM.
version: 1.0.0
repository: https://github.com/zaiehilmi/flutter_waktu_solat_my
documentation:

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  geolocator: ^10.1.0
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0