name: waktu_solat_malaysia
description: Ini ialah pakej untuk mendapatkan waktu solat di Malaysia berdasarkan jadual daripada JAKIM.
version: 1.0.4
repository: https://github.com/zaiehilmi/flutter_waktu_solat_my

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  test: ^1.24.3
